name: mva
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: bbarnes4318/mva
  dockerfile_path: Dockerfile
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xs
  envs:
  - key: NODE_ENV
    value: production
  - type: SECRET
    key: DATABASE_URL
    value: ${db.DATABASE_URL} 