name: mva
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: bbarnes4318/mva
  dockerfile_path: Dockerfile
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-2vcpu-2gb
  buildpacks:
    - name: nodejs
  features:
    - name: buildpack-stack
      value: ubuntu-22
  envs:
  - key: NODE_ENV
    value: production
    scope: RUN_AND_BUILD_TIME
  - key: PORT
    value: "8080"
    scope: RUN_AND_BUILD_TIME
  - type: SECRET
    key: DATABASE_URL
    value: ${db.DATABASE_URL}
  - type: SECRET
    key: EMAIL_USER
    value: ${EMAIL_USER}
  - type: SECRET
    key: EMAIL_PASS
    value: ${EMAIL_PASS}
  - type: SECRET
    key: PROXY_HOST
    value: ${PROXY_HOST}
  - type: SECRET
    key: PROXY_PORT
    value: ${PROXY_PORT}
  - type: SECRET
    key: PROXY_BASE_USER
    value: ${PROXY_BASE_USER}
  - type: SECRET
    key: PROXY_PASS
    value: ${PROXY_PASS}
  health_check:
    http_path: /
    initial_delay_seconds: 30
    period_seconds: 60
    timeout_seconds: 10
    success_threshold: 1
    failure_threshold: 3 